export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REM_INGREDIENT = 'REM_INGREDIENT';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const SET_ERROR = 'SET_ERROR';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS ='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL ='PURCHASE_BURGER_FAIL';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REMOVE_MESS = 'AUTH_REMOVE_MESS';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';